### ISSUE TITLE
Create dev environment

### ISSUE THREAD

**Issue by dawsonfi** [dawsonfi/ana-mastermind-game#6]

**Comment by cardosoana** [comment]
@dawsonfi pesquisando sobre a criação de ambientes no Travis, vi que eles tem a feature beta [Build Stages](https://docs.travis-ci.com/user/build-stages/). Com ela tem como escrever um travis.yml como por exemplo:

```jobs:
  include:
    - stage: unit tests
      script: "bundle exec rspec spec"
    - stage: deploy to dev
      script: skip
      deploy: &heroku
        provider: heroku
        app: dev-ana-mastermind-game
        api_key: $HEROKU_AUTH_TOKEN
      if: branch = master
    - stage: test dev
      script: 'curl http://dev-ana-mastermind-game.herokuapp.com/health'
      if: branch = master
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: ana-mastermind-game
      if: branch = master
    - stage: test production
      script: 'curl http://ana-mastermind-game.herokuapp.com'
      if: branch = master
```
Porém, pelo que pesquisei até agora, não é possível definir que determinado stage seja disparado manualmente (acho que seria o ideal, né? Ter um ambiente qa, testar e, só depois, colocar em produção, por exemplo)

Achei uma "[solução](https://stackoverflow.com/questions/44464477/trigger-a-travisci-build-stage-conditionally)" (gambiarra, talvez) que é criar uma branch pra cada ambiente, colocar as branches como condição nos stages e mergear quando quiser fazer o deploy. Acha que seria uma opção caso realmente não seja possível? Ou é melhor deixarmos tudo sendo triggado automaticamente?

**Comment by dawsonfi** [comment]
@cardosoana acho que funciona bem sim.
Quanto a subir direto pra prod, a ideia é essa mesmo, que cada commit que você faça, vá direto pra prod se todos os testes passarem. Assim todos os códigos que forem criados, serão sempre "production ready" :)

**Comment by cardosoana** [comment]
@dawsonfi mas faz sentido ter um ambiente de qa se eu não vou testar nada ali antes de ir pra produção ou um staging se não vai ser feito um showcase pra ninguem?

**Comment by dawsonfi** [comment]
@cardosoana a ideia do ambiente de QA, é que após o deploy, possamos executar testes funcionais automatizados, e, caso esses testes passem, ai sim fazemos o deploy para prod, tendo confiança que o sistema está funcionando bem.

E também, minha ideia com a criação de multiplos ambientes, mesmo que não vamos utilizar os mesmos diretamente, possamos exercitar a criação de configurações, toggles, etc em cada um desses ambientes.

**Comment by cardosoana** [comment]
Saquei! Beleza :)
