### ISSUE TITLE
Endpoint to create an user

### ISSUE THREAD

**Issue by dawsonfi** [dawsonfi/ana-mastermind-game#9]

**Comment by cardosoana** [comment]
É suficiente que um usuário tenha nome, email (ou login) e senha?

**Comment by dawsonfi** [comment]
Acredito que no momento, só precisamos de nome e id pro usuario.
A ideia desse endpoint é basicamente ter um usuario que joga o jogo, para guardarmos um histórico.

**Comment by cardosoana** [comment]
Certo! :)
